version: "2"
services:
  swagger:
    image: swaggerapi/swagger-ui
    volumes:
      - ./openapi.yaml:/usr/share/nginx/html/openapi.yaml
    environment:
      API_URL: openapi.yaml
    ports:
      - "8000:8080"
